### ISSUE TITLE
Error when generating seeds using certain options

### ISSUE THREAD

**Issue by Eatitup86** [abyssonym/terrorwave#4]
Getting the following error very often when using the following inputs (~60% of seed gens fail):
l2_terror_wave Lufia2.sfc iostwfourkeysmonstermashscale "" 0.72 1.0

```
Writing patches...
Loading and ranking game objects...
Randomizing treasure chests.
Randomizing items and equipment.
Randomizing an open world seed.
Randomizing monster movements.
Randomizing shops.
Analyzing key/lock requirements now.
Loop 0: ......
Loop 1: .
Done analyzing.
Assigning items to locations.
Traceback (most recent call last):
  File "randomizer.py", line 6969, in <module>
  File "randomizer.py", line 6498, in make_open_world
  File "random.py", line 222, in randint
  File "random.py", line 200, in randrange
ValueError: empty range for randrange() (0,0, 0)
```

**Comment by abyssonym** [comment]
Should be resolved in V3.15
